apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: drdroid-agent
    release: {{ .Release.Name }}
data:
  drdroid-collector-config: |-
    {{- toYaml .Values.configMap.data | nindent 4 }}
